### ISSUE TITLE
Reminder: Update `py39cloud` branch with next release

### ISSUE THREAD

**Issue by jdblischak** [TileDB-Inc/tiledbsoma-feedstock#229]
Note to self: with the next release of TileDB-SOMA, we need to update main as well as the branch [py39cloud](https://github.com/TileDB-Inc/tiledbsoma-feedstock/tree/py39cloud)

We will only need to maintain the separate py39cloud branch for as long as we continue to maintain the py39 TileDB Cloud env. Hopefully the transition to py312 will not be protracted (and thus it's not worth updating our release guidelines)

cc: @johnkerl

**Comment by jdblischak** [comment]
@johnkerl reminder that we can't forget this step. When you open the update PR for 1.15.0 to merge into main, then I'll adapt your PR and submit one to the branch py39cloud

**Comment by johnkerl** [comment]
> and thus it's not worth updating our release guidelines

I need to document _what I do for as long as I have to do it_ -- this is why I have the release procedure -- I'll update it right now

**Comment by jdblischak** [comment]
Closed by #239 (GitHub only auto-closes an Issue when its linked PR is merged into main)
