### ISSUE TITLE
Reminder: update requirements for 1.15.0

### ISSUE THREAD

**Issue by jdblischak** [TileDB-Inc/tiledbsoma-feedstock#233]
Another reminder Issue. The forthcoming 1.15.0 makes various updates to the requirements, and I'm having trouble keeping track of all of them.

libtiledbsoma:
* `tiledb >=2.27.0,<2.28`
* Remove the workaround code I had previously added to install tiledb 2.26.1 for the osx-64 build

tiledbsoma-py:
* ~~`somacore ==1.0.24`~~ `somacore ==1.0.26`
* ~~Remove tiledb-py~~ Move tiledb-py to test requirements
* **New:** Pin `scipy <1.15.0` (https://github.com/single-cell-data/TileDB-SOMA/issues/3444)

r-tiledbsoma:
* `r-rcppspdlog >=0.0.19`
* Bump r-tiledb

**Comment by johnkerl** [comment]
Thanks @jdblischak !

**Comment by jdblischak** [comment]
We also need to remove `fmt` once we've migrated to C++20 (likely won't happen for 1.15) (https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/230#issuecomment-2501865302)

**Comment by jdblischak** [comment]
@johnkerl Just remembered this Issue. I updated to reflect the latest requirements for 1.15.0.

In regards to the pre-check PR in https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/237, we included everything except `r-rcppspdlog >=0.0.19`. However, I confirmed that `r-rcppspdlog 0.0.19` was installed in [all 3 builds](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=41546&view=results), so this won't be a problem.
